### ISSUE TITLE
Default server set up requires a users database

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#57]
When I try to connect to a local server, client says nothing and the server continuously spams:

    ERROR: could not open 'config/users.gz' for reading
    ERROR: could not open 'config/groups.gz' for reading
    ERROR: could not open 'config/users.gz' for reading

I gather this means it's trying to load users & groups.
(1) I'd suggest that when there is no configuration, User ID and Group ID accepted blindly and logs indicate that.

This is important for development where you just want to connect to a local server without much difficulty.

(2) On the other hand if we want to require users.gz/groups.gz, the server should quit immediately at the start with an error, and we could perhaps provide a users.gz/groups.gz reference.

What do you think?

**Comment by lucasgautheron** [comment]
Currently, one cannot join a server without successfully authenticating 
https://github.com/ActionFPS/ActionFPS-Game/blob/master/source/src/server.cpp#L2768

What about a switch to launch a server in no-authentication mode ?
If this switch is enabled, then we do (1)
Otherwise, (2) (server stops on startup if these files can't be found)

**Comment by ScalaWilliam** [comment]
Sure. Is that a lot of work or not?

I'm aiming for minimal work on your and my part :)

**Comment by ScalaWilliam** [comment]
test

**Comment by ScalaWilliam** [comment]
dw

**Comment by lucasgautheron** [comment]
??

**Comment by ScalaWilliam** [comment]
testing the discord integration
